// `.env.ts` is generated by the `npm run env` command

export const environment = {
  production: true,
  version: '1.0.0',
  serverUrl: 'https://api.chucknorris.io',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US', 'fr-FR']
};
export const GRAPHQL_URL = 'https://cynthesize-hasura.herokuapp.com/v1alpha1/graphql';
export const REALTIME_GRAPHQL_URL = 'wss://cynthesize-hasura.herokuapp.com/v1alpha1/graphql';
export const authClientId = 'tEbTH2wRl3dHtWZ0m4nqoWPsN1GIu9dQ';
export const authDomain = 'cynthesize.auth0.com';
export const auth0Audience = 'https://cynthesize.auth0.com/userinfo';
export const callbackUrl = 'https://cynthesize-develop.netlify.app/';
